### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by CaptainZidgel** [bkacjios/lua-mumble#3] opened 2019-12-13 22:11 UTC
~I know you probably don't have notifications for this and this is a stupid question but if i'm being honest, I have no idea how to compile this. I'm a Lua programmer, not a C programmer, gosh darnit.
I compiled protoc as necessary, moved the headers into the folder as needed, and then i just kept re running make and downloading any headers I needed after that it started throwing errors in the mumble.c and it said a bunch of packages were not found in the pkg-config-path environment variable.
Any chance you have some binaries for Windows or Linux on hand?~
Ok, I've successfully compiled. I still think official binaries or comp instructions would be helpful, but I'm going to leave my process below in case anyone else wants to build this but doesn't know how. (instructions for Linux)
Clone the repository, and then use the command make or make -f makefile inside of the directory. It will start to tell you you're missing certain packages like protobuf-c or openssl or vorbis. Whenever it does that, do sudo apt-get install lib[package]-dev where [package] is what you were missing, so the first thing you'll probably run into is no protobuf-c/protobuf-c.h file. So you would do sudo apt-get install libprotobuf-c-dev . Just keep installing those packages and then `make`ing until it doesnt fail any more. Then you'll be able to require Mumble in Lua.

**Comment by bkacjios** [comment] 2019-12-15 18:58
Yup, that sounds about right for getting it to compile. I'll add it to the readme when I find some time. At the moment, this module will only work in linux as I'm using pthreads. I've been thinking of updating this to libuv instead to allow it to work on windows.

**Comment by CaptainZidgel** [comment] 2019-12-15 19:54
> I've been thinking of updating this to libuv instead to allow it to work on windows.

Would that be the official end of your support for this module or do you have any more updates you might implement at some point in the future?

**Comment by bkacjios** [comment] 2019-12-15 20:33
That would probably be it. I don't really know what other features I could implement.

**Comment by CaptainZidgel** [comment] 2019-12-15 22:11
If I were to suggest a few, the ability to link/unlink voice channels would be nice, Something like channel:Link(channel2, [optional channel3])
Also a bool in message() for whether or not to send a message recursively to subchannels would be neat, although a user could write their own function to utilize getChildren() to do that manually, but it would be inconvenient..
Also maybe I'm going about this the wrong way but I can't seem to use stateless iterators on tables returned from the library? I thought it was maybe that they were just all userdata, but that's not true. client:getUsers() returns a true table with real keys where the vals are userdata, but I can't run ipairs/pairs on it. If I want to iterate on it, I have to first set a variable to the value, like
```
local users = client:getUsers() 
for i,v in ipairs(users) do
```

which isn't that tedious to do once but it adds up over time. Maybe I just did something wrong but if that's the intended functionality I would recommend changing it, although it's a lower priority suggestion.

I really really appreciate you making this module, by the way! The only other viable lua-scripted mumble bot API i've found is written in a Lua VM in Go, so you can't use other DLLs which really knee caps what the script can do with external libs.

**Comment by bkacjios** [comment] 2019-12-15 23:45
Hmm, that seems weird that iterators aren't working correctly for you. I only return a table of users that's cached in the registry, and I don't modify __index or any other meta methods that would cause interference. 

https://github.com/bkacjios/lua-mumble/blob/master/client.c#L303

Plus, when I made my afk example I use pairs on the call directly https://github.com/bkacjios/lua-mumble/blob/master/examples/afk.lua#L40 and I remember it working fine.

Linking can be easily implemented, sure. The problem is I don't really use this module any more. I use my https://github.com/bkacjios/Lumble library instead. It's basically this module re-written using mostly pure lua, luajit's and its FFI library, plus some other well known lua C modules. The problem is it's way more of a pain to setup than this one. I've been thinking of porting it to Luvit, which is basically LuaJit+Libuv, but I haven't really had a reason to.

**Comment by CaptainZidgel** [comment] 2019-12-16 00:48
> 
> 
> Hmm, that seems weird that iterators aren't working correctly for you. I only return a table of users that's cached in the registry, and I don't modify __index or any other meta methods that would cause interference.
> 
> https://github.com/bkacjios/lua-mumble/blob/master/client.c#L303
> 
> Plus, when I made my afk example I use pairs on the call directly https://github.com/bkacjios/lua-mumble/blob/master/examples/afk.lua#L40 and I remember it working fine.
> 


I'm probably losing my mind then because I just retried and it worked perfectly fine. I don't know what I was doing wrong before.  I guess all's well that ends well!

And as for linking, that's fine if you don't want to implement it, it's not really necessary for the purpose of the bot I'm working on. (Although I would really like a way to see which channels are linked to another!) Regarding lumble, whether or not you choose to work on it more I would really recommend adding build instructions and at least some basic usage docs! You never know who it will be useful to!
See, I didn't even know Lumble could've been used to make bots until you mentioned it as being an alternative to this (although I'm getting pretty far with lua-mumble and probably wouldn't switch over, it might be beneficial to other potential users if they just started with Lumble, but then again I highly doubt the popularity of lua-scripted mumble bots.).

**Comment by bkacjios** [comment] 2019-12-16 19:40
Ok so..

I added these

```
mumble.channel:link(mumble.channel ...)
mumble.channel:unlink(mumble.channel ...)
Table mumble.channel = mumble.channel:getLinks()
```

It compiles, but I couldn't test to make sure they actually work. I also added the needed packages for compilation to the readme.

**Comment by CaptainZidgel** [comment] 2019-12-16 20:21
I only had 5 minutes to try them out, I can check later when I have more time to see if I had errors in my code/compile but I don't think they work (tried all three methods).
(It might be possible my code wasn't requiring the newly updated module (I compiled into a different folder to be sure) but I think if that were the case, I would have gotten an error for channel:link() not existing?)
Made sure the bot had mod and I was calling the method on a proper channel object by simultaneously sending a message to the same channel, which worked.
Didn't get any errors like an unknown method or missing/too many parameters, but there was no linking or unlinking action, and I couldn't get a table of the linked channels.

**Comment by bkacjios** [comment] 2019-12-16 21:47
Alright, channel linking is a lot more complicated than I thought. I have getLinks working, but adding/removing links is a problem for me at the moment.. Still trying to figure out how it works exactly.

**Comment by bkacjios** [comment] 2019-12-16 22:09
Okay, committed some changes. From what I tested it works.

**Comment by CaptainZidgel** [comment] 2019-12-16 22:24
Channel linking works like a charm! Thanks a lot!
I think the getLinks() misses out on a few channels though.. I'm going to keep testing and edit this later if I determine there's an issue or I just coded my loop wrong.

**Comment by bkacjios** [comment] 2019-12-16 22:29
It's possible I'm doing something wrong with the links_add or links_remove event and the links list is getting out of sync with the server.

**Comment by CaptainZidgel** [comment] 2019-12-16 22:31
Yeah, there are definitely some channels missing after a certain point but I don't know what's causing it. I don't know if they're getting lost when you initially check for all links (the channels I'm testing were linked before the script started) or what. If I specifically link them after the script starts they're not detected, it doesn't seem to be an issue with parenting, if I create new channels and link them they get picked up by the script...

**Comment by bkacjios** [comment] 2019-12-16 22:38
It seems fine to me. Are you calling getLinks immediately after calling a link or unlink? That's not going to work since the server has to confirm the change and then sync it with the bot via the OnChannelState hook, usually on the next update call.

Here's what I was using to test.

```lua
local mumble = require("mumble")

local client = assert(mumble.connect("localhost", 10004, "bot.pem", "bot.key"))

client:auth("Mumble-Bot")

client:hook("OnServerSync", function(event)
	print("OnServerSync", event)

	local chan1 = client:getChannel("Amers Anteater Corner")
	local chan2 = client:getChannel("An Absolute Classic")
	local chan3 = client:getChannel("MONKEY BREAD")

	client.me:move(chan1)

	--chan1:link(chan2, chan3)
	--chan2:link(chan1)

	chan1:link(chan2)
end)

client:hook("OnChannelState", function(channel)
	--if not client:isSynced() then return end

	print("OnChannelState", channel)

	for k,v in pairs(channel:getLinks()) do
		print(k,v)
	end
end)

while client:isConnected() do
	client:update()
	mumble.sleep(0.01)
end
```

**Comment by CaptainZidgel** [comment] 2019-12-16 22:59
Ah, that would be the problem then. Thanks!

**Comment by bkacjios** [comment] 2019-12-16 23:14
Great! Also worth mentioning I just committed another change. client:update() will be a lot faster. If say the server sent multiple packets at once, an update call would only read one, but now it will read everything it can. This significantly speeds up the connection process. Plus fixed a possible segfault with mumble.connect.

**Comment by CaptainZidgel** [comment] 2019-12-17 01:52
I have one last issue to report tonight (~this is from the build before your latest commit, I'll try in a second to see if it happens to be fixed there in some way~ It still happens in the latest commit (
9c8c75e)). I don't remember this happening earlier when I was initially checking if link and unlink methods worked because they worked fine, but I must not have tested thoroughly enough? Or there's some problem in my code.
The issue is that mumble.channel:unlink() with two parameters will crash the bot with this error:
```
realloc(): invalid next size
Aborted (core dumped)
```
It appears to happen if you call for it to unlink 2 channels, like so: addup:unlink(red, blu). addup:link(red, blu) has no issue with linking two at once.
I have no memory of it doing this earlier, but it does this anyway. Works fine doing only one.
Not the biggest issue of course, one could just run a:unlink(b) and a:unlink(c) one after the other.
Of interest to you may be the block I call the method from (in the onmessage hook), but I will say that I've commented out all of these lines at one time or another to find an issue, so i'm 90% certain it's only the method itself.
```
if string.find(msg, "!unlink", 1) == 1 then
			local server = tonumber(msg:sub(9,9))
			if server == 1 then
				server = channelTable.room1
			elseif server == 2 then
				server = channelTable.room2
			elseif server == 3 then
				server = channelTable.room3
			end
			local red, blu = server.red.object, server.blu.object --i've verified these are really mumble.channel objects and they can be unlinked individually.
			addup:unlink(blu, red)
			blu:unlink(red) --ive tried commenting this out and it doesn't change the result.
		end
```
Alright, I'm going to compile the new commit and see if it happens there as well.
edit: Yup, still happens in the latest build.

**Comment by bkacjios** [comment] 2019-12-17 03:04
Ok, was able to replicate it. Fixed it up and should be good now. Changed everything to use linked lists.

**Comment by CaptainZidgel** [comment] 2019-12-17 03:37
Great, thank you very much! I really appreciate you implementing these additions for me.

**Closed as completed** 2020-04-27 02:44 UTC
Labels: enhancement, help wanted
